---
name: Build Conda Image
description: Create a container with a specific Conda environment pre-installed
inputs:
  # Github repo access
  github-token:
    description: A Github repo access token
    required: true

  # Registry Access
  registry-name:
    decription: Container registry location
    default: ghcr.io
  registry-username:
    description: Username for container registry access
    default: ${{ github.actor }}
  registry-password:
    description: Password or token for container registry access
    required: true

  # Container Image Spec
  image-name:
    description: 'The base name of the image to create'
    default: ${{ github.repository }}-miniconda3-cache
  image-tag:
    description: 'The tag to apply to the image'
    required: true
  use-cache:
    description: 'Skip the building of the image if it is already cached'
    default: 'true'

  # Miniconda configuration parameters
  conda-rc:
    description: Set the sources for conda packages for the image
    default: conda-rc.yaml
  conda-env:
    description: The environment spec file
    default: conda-env.yaml
  conda-python:
    description: The version of python to use in the container
    required: true

outputs:
  image-id:
    description: A greeting from an action
    value: steps.build.outputs.image-id

#  docker-image:
#    description: 'The Docker image with the loaded environment'
#    value: ${{ steps.build.outputs.image }}

runs:
  using: composite
  steps:
    - name: Run the build script
      id: build
      shell: bash
      run: |
        ${{ github.action_path }}/build-image.sh
      env:
        GITHUB_TOKEN: ${{ github.inputs.github-token }}
        
        REGISTRY_NAME: ${{ github.inputs.registry-name }}
        REGISTRY_USERNAME: ${{ github.inputs.registry-username }}
        REGISTRY_PASSWORD: ${{ github.inputs.registry-password }}

        IMAGE_NAME: ${{ github.inputs.image-name }}
        IMAGE_TAG: ${{ github.inputs.image-tag }}
        IMAGE_CACHE: ${{ github.inputs.use_cached }}

        CONDA_RC: ${ github.inputs.conda-rc }}
        CONDA_ENV: ${{ github.inputs.conda-env }}
        CONDA_PYTHON: ${{ github.inputs.conda-python }}

  
