---
name: Build Conda Image
description: Create a container with a specific Conda environment pre-installed
inputs:
  # Registry Access
  registry-url:
    decription: Container registry location
    default: ghcr.io
  registry-username:
    description: Username for container registry access
    required: true
  registry-password:
    description: Password or token for container registry access
    required: true

  # Container Image Spec
  image-name:
    description: 'The base name of the image to create'
    default: ${{ github.repository }}-miniconda3-cache
  image-tag:
    description: 'The tag to apply to the image'
    required: true
  use-cache:
    description: 'Skip the building of the image if it is already cached'
    default: 'true'
    
outputs:
  greeting:
    description: A greeting from an action
    value: steps.build.outputs.image-id

#  docker-image:
#    description: 'The Docker image with the loaded environment'
#    value: ${{ steps.build.outputs.image }}

runs:
  using: composite
  steps:
    - name: Run the build script
      run: |
        ${{ github.action_path }}/build-image.sh
      shell: bash
      id: build
  
  
